services:
    auth_service:
        build:
            context: ./services/auth_service
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            DEVELOPMENT_MODE: true
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            REDIS_PASSWORD: ${REDIS_PASSWORD}

        ports:
            - "8000:443"

        volumes:
            - ./crypt_keys/jwt_keys:/auth_service/crypt_keys/jwt_keys:ro

        depends_on:
            database_migrations:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy

        healthcheck:
            test: [ "CMD", "curl", "http://auth_service/health" ]
            interval: 30s
            timeout: 20s
            retries: 3
            start_period: 10s


    database_migrations:
        build:
            context: ./services/database_migrations
            dockerfile: Dockerfile
        restart: on-failure
        #command: "alembic revision --autogenerate -m \"add_user_table\""
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./services/database_migrations/migrations/versions:/database_migrations/migrations/versions
        depends_on:
            postgres:
                condition: service_healthy


    
    redis:
        image: redis:8.2.2-alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./redis_data:/data
            - ./configurations/custom_configs/redis:/config/

        command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
        healthcheck:
            test: [ "CMD", "redis-cli", "-u", "redis://:${REDIS_PASSWORD}@localhost:6379", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s


    postgres:
        image: postgres:18-alpine
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data

        volumes:
            - ./postgres_data:/var/lib/postgresql/data

        healthcheck:
            test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
            interval: 10s
            timeout: 3s
            retries: 3
            start_interval: 10s
            start_period: 0s