"""add_token_version_uuid

Revision ID: 33df59363c17
Revises: 5fe12f45695b
Create Date: 2026-10-07 18:00:43.766216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33df59363c17'
down_revision: Union[str, Sequence[str], None] = '5fe12f45695b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version_uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version_uuid')
    # ### end Alembic commands ###
